### ISSUE TITLE
asTypeOrDefault: default values instead of null

### ISSUE THREAD

**Issue by IchordeDionysos** [passsy/deep_pick#8]
It would be cool if I could provide a default value instead of just getting null.

Yes, I could easily do this:
```dart
pick(json, 'shoes', 1, 'tags', 0).asStringOrNull() ?? "no tag";
```

But I would find this more readable and descriptive:
```dart
pick(json, 'shoes', 1, 'tags', 0).asStringOrDefault("no tag");
```

**Comment by passsy** [comment]
Thanks for your feedback. I agree that `orDefault` is easier readable. But `??` has a major advantage. The compiler only executes the part after `??` when the value is `null`. A method *always* executes the parameters right away.

Try it on [DartPad](https://dartpad.dev/3c884a82f6937e90bc132626e63321b1)
```dart
void main() {
  final String name = "Adam";

  print("=== ?? ===");
  // does not execute defaultValue()
  print(name ?? defaultValue());

  print("=== orDefault ===");
  // executes defaultValue()
  print(name.orDefault(defaultValue()));
}

String defaultValue() {
  print("execute defaultValue()");
  return "Charles";
}

extension Ext<T> on T {
  T orDefault(T defaultValue) {
    if (this == null) return defaultValue;
    return this;
  }
}
```

Output:
```
=== ?? ===
Adam
=== orDefault ===
execute defaultValue()
Adam
```



Another concern I have are two methods in you PR #9:
- `R letOrDefault<R>(R defaultValue, R Function(RequiredPick pick) block)`
- `List<T> asListOrDefault<T>(List<T> defaultValue, [T Function(Pick) map])`

To me those two parameter methods aren't easier to read than their `orNull + ??` counterpart because the defaultValue comes before the actual parameter of the method.

**Comment by passsy** [comment]
Closing this for now. If more people would find this useful please upvote this issue.
